DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;

CREATE TABLE authors(
id INT AUTO_INCREMENT PRIMARY KEY,
fio VARCHAR(250) NOT NULL,
description VARCHAR(500) DEFAULT NULL
);

CREATE TABLE  books(
id INT AUTO_INCREMENT PRIMARY KEY,
author INTEGER NOT NULL,
title VARCHAR(250) NOT NULL,
priceOld  VARCHAR(250) DEFAULT NULL,
price VARCHAR(250) DEFAULT NULL
);

ALTER TABLE books
    ADD FOREIGN KEY (author)
        REFERENCES authors (id)
;